### PR TITLE
improve footer

### PR DESCRIPTION
**Pull request by harshraj8843**
### Why:

- improve footer

### What's being changed:

Screenshot from 2022-12-17 19-04-24
Screenshot from 2022-12-17 19-04-15

### CODE REVIEW

**Review by anandfresh — APPROVED** [review]

**Review by tanishq-singh-2301 — APPROVED** [review]

**Comment by victoriacheng15** [comment]
@harshraj8843 I think you should make the `< >` to look same as the logo `</>`

**Comment by harshraj8843** [comment]
> @harshraj8843 I think you should make the `< >` to look same as the logo `</>`

I think the same, but it seems like [`mui`](https://mui.com/material-ui/material-icons/) doesn't have that icon, or I am unable to find it.

Check if you can find it here 👉🏻 https://mui.com/material-ui/material-icons/

Or should we make it simple text `</>`

**Comment by victoriacheng15** [comment]
> > @harshraj8843 I think you should make the `< >` to look same as the logo `</>`
> 
> I think the same, but it seems like [`mui`](https://mui.com/material-ui/material-icons/) doesn't have that icon, or I am unable to find it.
> 
> Check if you can find it here 👉🏻 https://mui.com/material-ui/material-icons/
> 
> Or should we make it simple text `</>`

Ah I see. Um, I think you could make one with Figma or similar software.

**Comment by harshraj8843** [comment]
> Ah I see. Um, I think you could make one with Figma or similar software.

Sure, I will try 😃 

I have one more idea. What about?

```
<> with ❤️ by </>
```

**Comment by victoriacheng15** [comment]
> > Ah I see. Um, I think you could make one with Figma or similar software.
> 
> Sure, I will try 😃
> 
> I have one more idea. What about?
> 
> ```
> <> with ❤️ by </>
> ```

I just checked the website folder and noticed that we have a `LOGO.png`. Can we use it with `with ❤️ by Codinasion`? I would keep the name in word isntead.

**Comment by harshraj8843** [comment]
The logo may not be appropriate (start with logo and end with name)

1. Screenshot from 2022-12-18 12-41-51
2. Screenshot from 2022-12-18 12-42-54

---

### Other options

We have also a few other options to choose

3. Screenshot from 2022-12-18 12-36-00
4. Screenshot from 2022-12-18 12-35-17
5. Screenshot from 2022-12-18 12-34-20

@anandfresh @tanishq-singh-2301 @joao-vitor-souza @grraghav120 please share your thoughts regarding this, as this style will be implemented across all the codinasion websites

**Comment by victoriacheng15** [comment]
I like ones with `</>`.  As for the heart colour, I would go with green since the site has green circles for programming languages.

**Comment by tanishq-singh-2301** [comment]
I personally like the plane grey one `i.e 5th`

**Pull request merged**
